In [21]:
import torch
import numpy as np 
import pandas as pd

In [2]:
x = 4.1 
y = torch.tensor(x)
print(y.ndim)
print(y.shape)

0
torch.Size([])


In [12]:
y = torch.tensor([3.,4.,5.], requires_grad = True, device = 'mps')
print(y.ndim)
print(y.requires_grad)
print(y.device)

1
True
mps:0


In [ ]:
a = torch.arange(3,8,2)
print(a.ndim)
print(a.dtype)  

1
torch.int64


In [20]:
#creates tensor using number of steps
a = torch.linspace(10,30,11)
print(a)

tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30.])


In [22]:
arr = np.array([3,4,5])
t = torch.tensor(arr)
t

tensor([3, 4, 5])

In [25]:
a = torch.zeros(size = (3,))
a

tensor([0., 0., 0.])

In [34]:
a = torch.zeros(size = ())
print(a.dtype)

torch.float32


In [33]:
a = torch.ones(size = ())
print(a.dtype)

torch.float32


In [32]:
x = torch.empty(size = ())
print(x)
print(x.dtype)

tensor(0.)
torch.float32


In [36]:
x = torch.eye(4,7)
x

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.]])

In [37]:
x = torch.ones(size = (3,4)) * 5
x

tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

In [39]:
x = torch.fill(x, value = 10)
x

tensor([[10., 10., 10., 10.],
        [10., 10., 10., 10.],
        [10., 10., 10., 10.]])

In [41]:
x = torch.randint(1,5,size = (3,2))
x

tensor([[4, 2],
        [3, 3],
        [3, 1]])

In [44]:
x = torch.randn(size = (3,4))
x

tensor([[-1.3961,  0.4907,  1.5130,  0.5632],
        [ 0.3866,  0.4464,  0.1297,  0.0577],
        [-0.0080, -1.4881, -0.5135,  0.0211]])

In [47]:
x = torch.normal(mean = 0, std = 5, size = (3,2))
x

tensor([[  6.0821, -13.5034],
        [  1.2140,   5.1320],
        [  6.2584,  -2.2022]])

In [55]:
ints = torch.randint(1,5,(3,),device = "mps")
print(ints.dtype)
print(ints.device)
y = torch.ones_like(x)
print(y)
print(y.dtype)
print(y.device)


torch.int64
mps:0
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
torch.float32
cpu


In [56]:
#error because ints has dtype ints
z = torch.randn_like(ints)

TypeError: Unsupported type Long for operation normal:Undefined:Undefined

In [58]:
z = torch.randn_like(torch.ones(size = (3,2)))
z

tensor([[ 0.7174, -0.6132],
        [ 1.0815,  0.1314],
        [-0.5704,  2.3832]])

In [ ]:
z.fill_(5)

tensor([[5., 5.],
        [5., 5.],
        [5., 5.]])

In [ ]:
z.fill_diagonal_(3)

tensor([[3., 5.],
        [5., 3.],
        [5., 5.]])

In [63]:
#requires grad nitty gritty
x = torch.tensor([3.,4.],requires_grad = True)
x.fill_(10)

RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.

In [68]:
x = torch.randn(size = (3,4), requires_grad = True, device = "mps")
print(x.shape)
x = x.numpy(force = True)
type(x)

torch.Size([3, 4])


numpy.ndarray

In [72]:
x = torch.randn(size = (3,4), requires_grad = True, device = "mps")
x1 = x.detach().to(device="cpu")
y = x1.numpy()
y

array([[-0.5333294 ,  0.75619465,  1.0720421 , -0.05867608],
       [-0.39252517, -1.5476542 ,  0.93363905,  0.40889305],
       [ 0.43154302, -0.63874835,  0.07892738,  0.5719641 ]],
      dtype=float32)