In [21]:
import torch
import numpy as np 
import pandas as pd

In [2]:
x = 4.1 
y = torch.tensor(x)
print(y.ndim)
print(y.shape)

0
torch.Size([])


In [12]:
y = torch.tensor([3.,4.,5.], requires_grad = True, device = 'mps')
print(y.ndim)
print(y.requires_grad)
print(y.device)

1
True
mps:0


In [ ]:
a = torch.arange(3,8,2)
print(a.ndim)
print(a.dtype)  

1
torch.int64


In [20]:
#creates tensor using number of steps
a = torch.linspace(10,30,11)
print(a)

tensor([10., 12., 14., 16., 18., 20., 22., 24., 26., 28., 30.])


In [22]:
arr = np.array([3,4,5])
t = torch.tensor(arr)
t

tensor([3, 4, 5])

In [25]:
a = torch.zeros(size = (3,))
a

tensor([0., 0., 0.])

In [27]:
a = torch.zeros(size = ())
a

tensor(0.)