In [90]:
import numpy as np

In [91]:
def kernel_function(x):
    t = np.outer(x,x)
    return (1 + t + 2*(t**2))**2


In [92]:
x = np.arange(5)
kernel_function(x)

array([[     1,      1,      1,      1,      1],
       [     1,     16,    121,    484,   1369],
       [     1,    121,   1369,   6241,  18769],
       [     1,    484,   6241,  29584,  90601],
       [     1,   1369,  18769,  90601, 279841]])

In [93]:
np.random.seed(2026)
A = np.random.randn(4, 6, 2, 1, 5)
A

array([[[[[-0.43171852, -1.39287397,  0.31157067, -0.01323488,
            1.44970773]],

         [[ 0.29815274, -0.82989603, -1.59615853,  0.6134378 ,
           -0.31759712]]],


        [[[-0.07399665, -0.6086309 , -1.99987301,  0.90824069,
            0.48297993]],

         [[ 0.22187845,  0.66402918, -1.24580681,  1.96887907,
           -0.31864893]]],


        [[[ 0.3597679 ,  0.74617104, -2.72485907,  1.67537886,
            0.0562327 ]],

         [[-1.69924546, -0.36135709,  2.72975002, -0.23884901,
           -1.42395841]]],


        [[[-0.16490147,  0.38537238, -0.62036584, -0.60293246,
            1.18107553]],

         [[ 0.83370308, -0.00587361, -0.06904386,  0.14635386,
           -0.4333855 ]]],


        [[[-0.01012728,  0.1365157 ,  1.47676095, -1.16648036,
            0.94003573]],

         [[ 1.67279158, -0.85689767,  0.18598594,  0.25180694,
           -0.16220392]]],


        [[[-0.4782721 , -0.99973132, -2.21205079,  0.5741506 ,
           -3.27252446]],



In [94]:
A = np.squeeze(A)
A.shape

(4, 6, 2, 5)

In [95]:
A = np.reshape(A, shape = (4,6,2,5))
A.shape

(4, 6, 2, 5)

In [96]:
A = np.expand_dims(A, 0)

In [97]:
A.shape

(1, 4, 6, 2, 5)

In [98]:
A = np.transpose(A, (2,0,3,1,4))
A.shape

(6, 1, 2, 4, 5)

In [99]:
A = np.flip(A, -1)
A.shape

(6, 1, 2, 4, 5)

In [100]:
mean = np.mean(A, axis = 1, keepdims = True)
mean.shape

(6, 1, 2, 4, 5)

In [101]:
axis_mean = np.mean(A, -1, keepdims = True)
print(axis_mean.shape)
axis_std = np.std(A, -1, keepdims = True) + 1e-8
print(axis_std.shape)

A = (A - axis_mean) / (axis_std)
A.shape

(6, 1, 2, 4, 1)
(6, 1, 2, 4, 1)


(6, 1, 2, 4, 5)

In [102]:
mask = (A < -1.5)
print(mask.sum())

A[mask] = 8

print("num replaced:", mask.sum())
print("min after replace:", A.min())

20
num replaced: 20
min after replace: -1.4870271535963921


In [118]:
mask_2 = (A >= 2)

new_arr = A[mask_2]
new_arr.shape

(20,)

In [120]:
indices = np.argmax(A, axis = 0)
indices.shape

(1, 2, 4, 5)

# Vectors

### Vector Creation

In [103]:
# Create a vector of numbers
v1 = np.array([1,2,3])
print(v1)

[1 2 3]


In [104]:
# Create a vector of 0's
v2 = np.zeros(3)
print(v2)

[0. 0. 0.]


In [105]:
# Create a vector of 1's
v3 = np.ones(4)
print(v3)

[1. 1. 1. 1.]


In [106]:
# Create a vector of random numbers
v4 = np.random.random(3)
print(v4)

[0.84794798 0.56406046 0.15038372]


In [107]:
# Create a vector of equally spaced values
v5 = np.linspace(0,2,9)
print(v5)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


### Vector Properties

In [108]:
# Dimension of vector v1
print(v1.ndim)

1


In [109]:
# Shape of vector v2
print(v2.shape)

(3,)


In [110]:
# Number of elements in v3
print(v3.size)

4


In [111]:
# Type of the elements in v3
print(v3.dtype)

float64


### Indexing And Slicing Into A Vector

In [112]:
v1 = np.array([1,2,3])
print(v1[0])

1


In [113]:
print(v1[1])

2


In [114]:
print(v1[0:2])

[1 2]


In [115]:
print(v1[1:])

[2 3]


### Vector Arithmetic

In [116]:
v1 = np.array([1,2,3])
v2 = np.zeros(3)
print(v1 + v2)

[1. 2. 3.]


In [117]:
v3 = np.ones(4)
print(v1 + v3)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
v4 = np.array([2, 3, 4])
print(v1 * v4)

In [ ]:
print(v1 / v4)

### Vector Aggregation

In [ ]:
v = np.array([1, 2, 3])
print(v.min())

In [ ]:
print(v.max())

In [ ]:
print(v.sum())

In [ ]:
print(v.mean())

# Matrices

### Matrix Creation

In [ ]:
# Create a matrix of numbers
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A)

In [ ]:
# Create a matrix of 1's
B = np.ones((2,3))
print(B)

### Matrix Properties

In [ ]:
# Dimension of matrix A
print(A.ndim)

In [ ]:
# Shape of matrix B
print(B.shape)

In [ ]:
# Number of rows in B
print(B.shape[0])

In [ ]:
# Number of columns in B
print(B.shape[1])

In [ ]:
# Number of elements in B
print(B.size)

In [ ]:
# Type of the elements in A
print(A.dtype)

### Indexing And Slicing Into A Matrix

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A[0,1])

In [ ]:
print(A[1:3])

In [ ]:
print(A[0:2,0])

In [ ]:
print(A[:,1])

### Matrix Arithmetic

In [ ]:
A = np.array([[1, 2], [3, 4]])
ones = np.ones((2,2))
print(A - ones)

### Matrix Aggregation

In [ ]:
A = np.array([[1, 2], [5, 3], [4, 6]])
print(A.min())

In [ ]:
print(A.max())

In [ ]:
print(A.sum())

In [ ]:
print(A.mean())

In [ ]:
print(A.cumsum())

In [ ]:
print(A.max(axis = 0))

In [ ]:
print(A.cumsum(axis = 1))

# Dot Product

In [ ]:
u = np.array([1, 2])
v = np.array([1, 2, 3])
A = np.array([[1, 2], [3, 4], [5, 6]])
B = np.array([[1, 2, 3], [4, 5 ,6]])
print(v.dot(v))

In [ ]:
print(u.dot(A))

In [ ]:
print(A.dot(u))

In [ ]:
print(v.dot(A))

In [ ]:
print(A.dot(v))

In [ ]:
print(A.dot(B))

In [ ]:
print(B.dot(A))

# Broadcasting

In [ ]:
v1 = np.array([1,2,3])
print(v1 * 1.5)

In [ ]:
print(v1 + 1)

In [ ]:
x = np.arange(4)
y = np.ones((3,4))
print(x + y)

# Resizing And Reshaping

In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6]])
print(A.transpose())

In [ ]:
v = np.arange(1, 7)
B = v.reshape(2, 3)
print(B)

In [ ]:
w = B.flatten()
print(w)

In [ ]:
C = w.reshape(2, -1)
print(C)

In [ ]:
v.resize(3, 2)
print(v)

# Combining Arrays

In [ ]:
A = np.ones((2,3))
print(np.vstack([A, 2*A]))

In [ ]:
print(np.hstack([A, 2*A]))

In [ ]:
v = np.ones(3)
print(np.vstack([v, 2*v, 3*v, 4*v]))


In [ ]:
print(np.hstack([v, v+10]))

In [ ]:
print(np.column_stack([v, v+10]))

# Copies And Views

* Simple assignments do not copy Numpy array objects
* If the new array is modified, the old array is modified also
* The view method creates a new array object that looks at the same data
* Slicing an array returns a view of it
* The copy method makes a complete copy of the array and its data
* The flatten() method makes a copy of a 2D array and flattens it as a 1D array
* The ravel() method creates a flattened view of the 2D array



In [ ]:
u = np.arange(1, 4)
v = u
print(v)

In [ ]:
u[0] = 10
print('u =', u)
print('v =', v)

In [ ]:
u = np.arange(1, 4)
w = np.copy(u)
u[0] = 10
print('u =', u)
print('w =', w)