In [2]:
import numpy as np
import pandas as pd

In [ ]:
def gram_schmidt_orthonormalization(V: np.ndarray):
    '''
    Constructs orthonormal basis orom a basis of space W 
    Inputs (shape (n,n)): V, where each column is a basis vector
    '''
    n = V.shape[0]
    V_T = V.T

    E = np.zeros((n,n))
    E[0] = V_T[0] / np.sqrt(np.sum(V_T[0]**2))
    R = np.zeros((n,n))
    for i in range(1,n):
        R[i] = V_T[i] - np.sum([np.dot(V_T[i], E[j]) * E[j] for j in range(i)], axis=0)
        #normalize residual 
        E[i] = R[i] / np.linalg.norm(R[i])
    
    return E.T


In [ ]:
def gram_schmidt_orthonormalization(V: np.ndarray) -> np.ndarray:
    """Construct an orthonormal basis from a set of linearly independent vectors.

    Parameters
    ----------
    V : np.ndarray, shape (n, n)
        Matrix whose columns are the input basis vectors.

    Returns
    -------
    E : np.ndarray, shape (n, n)
        Matrix whose columns form an orthonormal basis for the column space of V.

    Raises
    ------
    ValueError
        If a zero residual is encountered, indicating linearly dependent input vectors.
    """
    n = V.shape[1]
    E = np.zeros_like(V, dtype=float)

    for i in range(n):
        u = V[:, i].astype(float)
        for j in range(i):
            u -= np.dot(u, E[:, j]) * E[:, j]
        norm = np.linalg.norm(u)
        if norm < 1e-10:
            raise ValueError(f"Column {i} is linearly dependent on previous columns.")
        E[:, i] = u / norm

    return E


In [4]:
V = np.array([[1,2],[3,4]])
V[0]**2

array([1, 4])

In [ ]:
class My_Inner_Product:
    # def inner_product(A,B):
    #     n = A.shape[0]
    #     C = np.zeros(n)
    #     for i in range(n):
    #         C[i] = np.dot(A[i],B[i])
    #     return C
    def inner_product(A,B):
        return np.sum(A*B, axis = 1)
A = np.arange(6).reshape(3,2)
B = A + 1
print(A)
print(B)
print(My_Inner_Product.inner_product(A,B))

[[0 1]
 [2 3]
 [4 5]]
[[1 2]
 [3 4]
 [5 6]]
(3,)


In [ ]:
class My_Outer_Product:
    def outer_prod(A,B):
        # #non-vectorized version
        # n = A.shape[0]
        # d_0 = A.shape[1]
        # d_1 = B.shape[1]
        # C = np.zeros((n,d_0,d_1))
        # for i in range(n):
        #     C[i] = np.outer(A[i],B[i].T)
        # return C

        #vectorized version
        n, d_0 = A.shape
        d_1 = B.shape[1]
        C = A.reshape(n, d_0, 1) * B.reshape(n, 1, d_1)

        return C



A = np.arange(6).reshape(3,2)
B = A + 1
print(A)
print(B)
print(My_Outer_Product.outer_prod(A,B))